require_relative 'config/connection'
require_relative 'config/models'

namespace :db do
  desc "Run migrations"

  task :migrate do
    ActiveRecord::Migrator.migrate('db/migrate', ENV["VERSION"] ? ENV["VERSION"].to_i : nil)
  end

  desc "Run seeds"

  task :seed do
    require 'ffaker'

    150.times do
      lon = 55.986889 + rand - 0.5
      lat = 54.717261 + rand - 0.5

      Car.create(
        number: FFaker::Vehicle.vin,
        available: rand(0..1),
        lonlat: "POINT(#{lon} #{lat})",
        brand: "#{FFaker::Vehicle.make} #{FFaker::Vehicle.model}"
      )
    end
  end
end